demoone/urls.py
from django.contrib import admin
from django.urls import path, include
from mainsite.views import machinelearning, tv, f_unemployed, c_unemployed, model
from account.views import signin, signup, logoutUser, needhelp
from chat.views import contact, chat_post
from django.conf.urls import url
import chat.views as chat

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',machinelearning, name="home"),
    path('signin.html/', signin, name="signin"),
    path('signup.html/', signup, name="signup"),
    path('help/', needhelp, name="help"),
    path('logout.html/', logoutUser, name="logout"),
    path('mail/', contact, name="mail"),
    path('chat/', chat_post, name="chat_post"),
    path('chat/<int:pid>/<str:del_pass>',chat_post),
    path('chat/contact/', contact),
    url(r'^captcha', include('captcha.urls')),
    path('news/0/', tv, name="tv"),
    path('news/<int:tvno>/',tv,name='tv-url'),
    path('f_unemployed/', f_unemployed, name="f_unemployed"),
    path('c_unemployed/', c_unemployed, name="c_unemployed"),
    path('model/',model),
    ]

chat/models.py
from django.db import models

# Create your models here.
		
class Mood(models.Model):
	status = models.CharField(max_length=10, null=False)
	def __str__(self):
		return self.status

class Post(models.Model):
	mood = models.ForeignKey('Mood', on_delete=models.CASCADE)
	nickname = models.CharField(max_length=10, default='不願意透漏身份的人')
	message = models.TextField(null=False)
	del_pass = models.CharField(max_length=10)
	bday = models.CharField(max_length=10, default='')
	pub_time = models.DateTimeField(auto_now=True)
	enabled = models.BooleanField(default=True)

	def __str__(self):
		return self.message

class Mail(models.Model):
	user_name = models.CharField(max_length=20)
	# user_city = models.CharField(max_length=20)
	user_email = models.CharField(max_length=20)
	user_message= models.TextField(null=False)

	def __str__(self):
		return self.user_message

chat/forms.py
from django import forms
from . import models
from captcha.fields import CaptchaField


class ContactForm(forms.Form):
	CITY = [
		['TP', "Taipei"],
		['TY', "Taoyuang"],
		['TC', "Taichung"],
		['TN', "Tainan"],
		['KS', "Kaohsiung"],
		['NA', "Others"],
	]
	user_name = forms.CharField(label='您的姓名', max_length=50, initial='Victor')
	user_city = forms.ChoiceField(label='居住城市', choices = CITY)
	user_school = forms.BooleanField(label='是否在學', required=False)
	user_email = forms.EmailField(label='電子郵件')
	user_message = forms.CharField(label='您的意見', widget=forms.Textarea)

class PostForm(forms.ModelForm):
	captcha = CaptchaField()
	class Meta:
		model = models.Post
		fields = ['mood', 'nickname', 'message', 'del_pass']

	def __init__(self, *args, **kwargs):
		super(PostForm, self).__init__(*args, **kwargs)
		self.fields['mood'].label = '現在心情'
		self.fields['nickname'].label = '你的暱稱'
		self.fields['message'].label = '心情留言'
		self.fields['del_pass'].label = '設定密碼'
		self.fields['captcha'].label = '不是機器人'

class Mail(forms.ModelForm):
	user_name = forms.CharField(label='您的姓名', max_length=50, initial='Victor')
	user_email = forms.EmailField(label='電子郵件')
	user_message = forms.CharField(label='您的意見', widget=forms.Textarea)

	class Meta:
		model = models.Mail
		fields = ['user_name', 'user_email', 'user_message']

	def __init__(self, *args, **kwargs):
		super(Mail, self).__init__(*args, **kwargs)
		self.fields['user_name'].label = '姓名'
		self.fields['user_email'].label = '信箱'
		self.fields['user_message'].label = '內容'

chat/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from chat import models
from .import forms
from django.contrib.sessions.models import Session
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from datetime import datetime


# Create your views here.
@login_required(login_url='signin')
def chat_post(request, pid=None, del_pass=None):
	posts = models.Post.objects.filter(enabled = True).order_by('-pub_time')[:30]
	moods = models.Mood.objects.all()
	now = datetime.now()

	try:
		user_id = request.GET["user_id"]
		user_pass = request.GET["user_pass"]
		user_post = request.GET["user_post"]
		user_mood = request.GET["mood"]
	except:
		user_id = None
		message = '欄位皆必填'

	if del_pass and pid:
		try:
			post = models.Post.objects.get(id=pid)
		except:
			post = None
		if post:
			if post.del_pass == del_pass:
				post.delete()
				message= "刪除成功"
			else:
				message = "密碼錯誤"

	elif user_id!=None:
		m = models.Mood.objects.get(status = user_mood)
		post = models.Post.objects.create(mood = m, nickname = user_id, del_pass = user_pass, message = user_post)
		post.save()
		message = '儲存成功'

	return render(request, "chat.html", locals())

def contact(request):
	now = datetime.now()

	if request.method == "POST":
		form = forms.Mail(request.POST)
		if form.is_valid():
			user_name = form.cleaned_data['user_name']
			# user_city = form.cleaned_data['user_city']
			user_email = form.cleaned_data['user_email']
			user_message = form.cleaned_data['user_message']
			message = "感謝來信"
			form.save()
		else:
			message = "資料不正確"
	else:
		form = forms.Mail()	
	return render(request, 'chat/contact.html', locals())

templates/chat/contact.html
{% extends '../base.html' %}
{% load static %}
{% block title %} 資管系畢業專題 {% endblock %}
{% block headmessage %}
<style>
	.panel-body p{
		color: #ffffff;
	}

	.panel-footer button{
		margin-left: 600px;
	}
</style>
{% endblock %}
{% block content %}
	<div class="container" >
	{% if message %}
		<div class="alert alert-info" style="color:#ffffff;;">{{ message }} {{ user_name }}</div>
	{% endif %}
	<div class="panel panel-primary">
		<div class="panel-heading">
			<form action="." method="POST" style="color: #ffffff;">
			<strong><big><big><h3 style="color: #67acb5;">寫信給管理員</h3></big></big></strong>
			{% csrf_token%}
		</div>
		<div class="panel-body" style="background-color: #ffffff;">
			<!-- <p>{{ form.as_p }}</p> -->
			<p>
				<label for="id_user_name"><font color="black">姓名：</font></label>
				<input id="id_user_name" type="text" name="user_name" value="" maxlength="50" required="" style="background-color: #ffffff;">
			</p>
			<p>
				<label for="id_user_email"><font color="black">信箱：</font></label>
				<input id="id_user_email" type="text" name="user_email" required="" style="background-color: #ffffff;">
			</p>

			<p>
				<label for="id_user_message"><font color="black">內容：</font></label>
				<textarea id="id_user_message" type="text" name="user_message" cols="120" rows="10" required="" style="background-color: #ffffff;"></textarea >
			</p>


		</div>
		<div class="panel-footer">
			<br>
			<button type="submit"  >送出</button>
		    </form>
		</div>
	</div>
</div>

{% endblock %}